import Head from 'next/head';
import React from "react";

import {getSession} from "next-auth/client";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import Contact from "../components/Contact";

export default function Home({session}) {
  const [state, setState] = React.useState(false);
  const [current, setCurrent] = React.useState({});
  const openChat = (user) => {
    setState(true);
    setCurrent(user);
  };
  const closeChat = () => {
    setState(false);
  };
  if (!session) return <Login />;
  return (
    <div >
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      
      <Header />

      <main  className="flex">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets openChat={openChat}  />

        <Contact state={state} current={current} closeChat={closeChat} />
      </main>
      
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return { 
    props: {
      session,
    },
  };
}